# Generated by Django 4.1.5 on 2023-01-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afloapp', '0002_rename_created_formation_createdat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='formation',
            name='eleves',
            field=models.ManyToManyField(blank=True, null=True, related_name='formations', to='afloapp.eleve'),
        ),
        migrations.AddField(
            model_name='formation',
            name='formateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='afloapp.formateur'),
        ),
        migrations.AddField(
            model_name='formation',
            name='information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formation', to='afloapp.information'),
        ),
    ]
